export const refs = {
  language: document.querySelector('.language'),
  changeOfTheme: document.querySelector('.theme'),
  slideTitle: document.querySelector('.slide__title'),
  footer: document.querySelector('.footer'),
  footerSupp: document.querySelector('.text-supp'),
  footerApp: document.querySelector('.text-app'),
  footerJoin: document.querySelector('.text-join'),
  footerEmail: document.querySelector('.email'),
  footerCopy: document.querySelector('.footer--copyright'),
  btnUa: document.querySelector('.btn-ua'),
  btnEng: document.querySelector('.btn-eng'),
  home: document.querySelector('#button__home'),
  library: document.querySelector('#button__library'),
  input: document.querySelector('.search__form--input'),
  placeholderText: document.getElementsByName('Search films'),
  sliderTitle: document.querySelector('.slide__title'),
  btnWatched: document.querySelector('#btn__watched'),
  btnQueue: document.querySelector('#btn__queue'),
  textApp: document.querySelector('.text-app'),
  appSupp: document.querySelector('.text-supp'),
  textJoin: document.querySelector('.text-join'),
  iconGoogleEn: document.querySelector('#google-play__en'),
  iconGoogleUa: document.querySelector('#google-play__ua'),
  iconStoreEn: document.querySelector('#app-store__en'),
  iconStoreUa: document.querySelector('#app-store__ua'),
  footerCopywrite: document.querySelector('.copyright'),
  footerStudents: document.querySelector('.students'),
  footerLink: document.querySelector('.students--link'),
};
