const users = [
  {
    id: '1',
    name: 'Roman Hyrych',
    role: 'Team lead',
    img: 'https://avatars.githubusercontent.com/u/88936471?v=4',
    ginHabLink: 'https://github.com/romanlancer/',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '2',
    name: 'Anna Nychyk',
    role: 'Scrum-мастер',
    img: 'https://avatars.githubusercontent.com/u/88631065?v=4',
    ginHabLink: 'https://github.com/AnnaNychyk',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '3',
    name: 'Lubov Danchenko',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/22094005?v=4',
    ginHabLink: 'https://github.com/LDanchenko',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '4',
    name: 'Evgeniy Ignatenko',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/75755667?v=4',
    ginHabLink: 'https://github.com/eijjeka',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '5',
    name: 'Viktoria Mihalyova',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/88782163?v=4',
    ginHabLink: 'https://github.com/MViktoriia',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '6',
    name: 'Aleksandr Serebro',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/88261876?v=4',
    ginHabLink: 'https://github.com/AlexSerebro',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '7',
    name: 'Oleksandr Nikolaienko',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/41318656?v=4',
    ginHabLink: 'https://github.com/aleksander-nikolaenko',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '8',
    name: 'Serhii Sakhno',
    role: 'Tech lead',
    img: 'https://avatars.githubusercontent.com/u/89796587?v=4',
    ginHabLink: 'https://github.com/SerhiiSakhno1994',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '9',
    name: 'Aleksandr Kashirin',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/88508533?v=4',
    ginHabLink: 'https://github.com/Saniokkk',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
];

export default users;
