export const users = [
  {
    id: '1',
    name: 'Roman Hyrych',
    role: 'Team lead',
    img: 'https://avatars.githubusercontent.com/u/88936471?v=4',
    ginHabLink: 'https://github.com/romanlancer/',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '2',
    name: 'Anna Nychyk',
    role: 'Scrum-master',
    img: 'https://avatars.githubusercontent.com/u/88631065?v=4',
    ginHabLink: 'https://github.com/AnnaNychyk',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '3',
    name: 'Lubov Danchenko',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/22094005?v=4',
    ginHabLink: 'https://github.com/LDanchenko',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '4',
    name: 'Evgeniy Ignatenko',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/75755667?v=4',
    ginHabLink: 'https://github.com/eijjeka',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '5',
    name: 'Viktoria Mihalyova',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/88782163?v=4',
    ginHabLink: 'https://github.com/MViktoriia',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '6',
    name: 'Aleksandr Serebro',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/88261876?v=4',
    ginHabLink: 'https://github.com/AlexSerebro',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '7',
    name: 'Oleksandr Nikolaienko',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/41318656?v=4',
    ginHabLink: 'https://github.com/aleksander-nikolaenko',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/in/aleksander-nikolaienko-426b20229/',
    discription:
      'I am a beginner Full Stack developer. I have completed courses in markup and javascript. I continue to study frameworks, such as react.js and node.js.',
  },
  {
    id: '8',
    name: 'Serhii Sakhno',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/89796587?v=4',
    ginHabLink: 'https://github.com/SerhiiSakhno1994',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '9',
    name: 'Aleksandr Kashirin',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/88508533?v=4',
    ginHabLink: 'https://github.com/Saniokkk',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
];

export const usersUA = [
  {
    id: '1',
    name: 'Гирич Роман',
    role: 'Лідер команди',
    img: 'https://avatars.githubusercontent.com/u/88936471?v=4',
    ginHabLink: 'https://github.com/romanlancer/',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '2',
    name: 'Анна Ничик',
    role: 'Scrum-мастер',
    img: 'https://avatars.githubusercontent.com/u/88631065?v=4',
    ginHabLink: 'https://github.com/AnnaNychyk',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '3',
    name: 'Любов Данченко',
    role: 'Розробник',
    img: 'https://avatars.githubusercontent.com/u/22094005?v=4',
    ginHabLink: 'https://github.com/LDanchenko',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '4',
    name: 'Євген Ігнатенко',
    role: 'Розробник',
    img: 'https://avatars.githubusercontent.com/u/75755667?v=4',
    ginHabLink: 'https://github.com/eijjeka',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '5',
    name: 'Вікторія Міхайлова',
    role: 'Розробник',
    img: 'https://avatars.githubusercontent.com/u/88782163?v=4',
    ginHabLink: 'https://github.com/MViktoriia',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '6',
    name: 'Олександр Серебро',
    role: 'Розробник',
    img: 'https://avatars.githubusercontent.com/u/88261876?v=4',
    ginHabLink: 'https://github.com/AlexSerebro',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Дуже приємно працювати в такій команді!!!',
  },
  {
    id: '7',
    name: 'Олександр Ніколаєнко',
    role: 'Розробник',
    img: 'https://avatars.githubusercontent.com/u/41318656?v=4',
    ginHabLink: 'https://github.com/aleksander-nikolaenko',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/in/aleksander-nikolaienko-426b20229/',
    discription:
      'Я починаючий Full Stack розробник. Я закінчив курси з html та javascript. Продовжую вивчати фреймворки, такі як react.js та node.js.',
  },
  {
    id: '8',
    name: 'Сергій Сахно',
    role: 'Розробник',
    img: 'https://avatars.githubusercontent.com/u/89796587?v=4',
    ginHabLink: 'https://github.com/SerhiiSakhno1994',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '9',
    name: 'Олександр Каширін',
    role: 'Розробник',
    img: 'https://avatars.githubusercontent.com/u/88508533?v=4',
    ginHabLink: 'https://github.com/Saniokkk',
    FB_Link: 'https://www.facebook.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
];
